### ISSUE TITLE
=> ERROR [internal] load git source github.com/jupyter/docker-stacks.git#master:base-notebook

### ISSUE THREAD

**Issue by walter211** [dask/dask-docker#158] opened 2021-06-16 05:00 UTC
![image](https://user-images.githubusercontent.com/2074640/122160625-d8aa5f00-cea2-11eb-9ec8-b03be3817a9e.png)

**Comment by jacobtomlinson** [comment] 2021-06-16 09:06
Closing this as a duplicate of #156

**Closed by jacobtomlinson** 2021-06-16 09:06 UTC
